

all:

include ../pitch.mk


# you can uncomment matrix-lib-speed-test if you want to do the speed tests.

TESTFILE =

OBJFILES = kaldi-matrix.o kaldi-vector.o

LIBNAME = pitch-matrix

ADDLIBS = ../base/pitch-base.a 

include ../makefiles/default_rules.mk

