

all:

include ../kaldi.mk


# you can uncomment matrix-lib-speed-test if you want to do the speed tests.

TESTFILE =

OBJFILES = kaldi-matrix.o kaldi-vector.o

LIBNAME = kaldi-matrix

ADDLIBS = ../base/kaldi-base.a 

include ../makefiles/default_rules.mk

