all:

include ../kaldi.mk

TESTFILES =

OBJFILES = cmvn.o transform-common.o

LIBNAME = kaldi-transform

ADDLIBS = ../util/kaldi-util.a ../thread/kaldi-thread.a \
          ../matrix/kaldi-matrix.a ../base/kaldi-base.a

include ../makefiles/default_rules.mk
